### ISSUE TITLE
npm i 部分模块失效？无法安装依赖

### ISSUE THREAD

**Issue by dpc761218914** [inmyjs/apshop#2]

**Comment by inmyjs** [comment]
@dpc761218914  请反馈下错误信息，我的环境是win10,node8.11.4,安装是正常的。
![image](https://user-images.githubusercontent.com/19298710/47208520-a4fc9b80-d3c0-11e8-849a-d94123030a98.png)
![image](https://user-images.githubusercontent.com/19298710/47208554-b80f6b80-d3c0-11e8-8fce-5e7d2d183203.png)

**Comment by dpc761218914** [comment]
嗯嗯，感谢~有可能是我环境问题。
