### ISSUE TITLE
导入apshop_db_20171204.sql报错

### ISSUE THREAD

**Issue by ray-zyh** [inmyjs/apshop#4]
用navicat 导入apshop_db_20171204.sq提示如下错误,数据没有导入成功

ALTER TABLE config COMMENT= '系统配置表';
-- ----------------------------------------------------------------
-- 文档表: document
-- 建立: kunoy 20171101
-- 
-- ----------------------------------------------------------------
DROP TABLE IF EXISTS document;
CREATE TABLE document
(
did					INT AUTO_INCREMENT				
[SQL] Finished with error

**Comment by inmyjs** [comment]
是mysql版本的问题，这个脚本是在windows mysql5.7中写的脚本，在linux环境中大小写敏感，所以有点问题，近期我修复一下。

**Comment by inmyjs** [comment]
已更新1.1版本
