### ISSUE TITLE
为什么我启动项目以后，后台获取不到数据库对象？

### ISSUE THREAD

**Issue by fengyangsy** [inmyjs/apshop#7]
const Op = ctx.model.Op;
这个Op是null，读取数据库失败
我是在Windows7上面部署的，数据库是mysql5.7，data中的三个文件都已执行过了。

**Comment by fengyangsy** [comment]
刚看见config中有两个文件都包含了连接数据库信息，是否都需要修改，我只按照说明改了一个？

**Comment by inmyjs** [comment]
应该是数据库连接不上，两个原因：1.分配的数据库账号没有连接权限，这个要配置mysql账号权限；2.node.js的mysql连接库有问题，可以重新装一下。
config中的配置一个是开发环境，一个是正式环境，看启动项目时是以什么环境方式启动的。

**Comment by inmyjs** [comment]
是egg-sequelize新版本的问题，改了api。
