### ISSUE TITLE
执行sql报错

### ISSUE THREAD

**Issue by PrintingChen** [inmyjs/apshop#9]
[Err] 1067 - Invalid default value for 'create_Time'
[Err] /*===============================================================*/
-- apshop平台数据结构
-- inmyjs 20190101
-- 版本 V1.0.171101
-- ---------------------------------------------------------------
-- 文档需要对齐, Tab键设置为4个空格
-- 表的备注: 如: --序号表: Sequence
-- 字段名注释规范: 单行注释标志COMMENT+字段中文抬头+半角左括号+标志及详细说明+半角右括号。
-- 举例字段的备注: COMMENT '字典状态(*, 0=正常, S=失效)'。
-- 表命名规则: 以大小写英文来进行命名, 太长的英文可采用尽可能的规范缩写。
-- 字段命名规则: 以英文大小写进行命名, 多层意思中间用_连接, 部分常用字段可不用_连接。
-- 所有的ID都不用连接符_, 因为使用频率很高。
-- 核心ID字段采用单字缩写, 以方便未来的使用, 如: UID=用户ID, CID=客户ID, EID=设备ID, PID=产品ID
-- 非核心ID一般不用单字缩写, 如: LogID=日志ID, ORGID=机构ID, CommunityID=小区ID
-- 带*的字段是通过Wordbook字典来解释的
-- 部分字段规范：
-- 1、标识一般采用Flag, 数据类型一般是CHAR(1), 双态的标志用[Y]和[N]
-- 2、状态统一使用Status或以此为后缀的词
-- 3、备注全部使用Note, 数据类型是TEXT
-- 4、日期采用_Date为后缀, 类型是DATE, 时间采用_Time为后缀, 类型是DATETIME
-- 5、单据采用B_开头的表名, 以区别于其他对象
-- 标准状态采用Status, 其设置为: 0=正常, S=失效, P=暂停, N=新建/未转正/未开通
-- 部分常用于计算的表名有部分约定, 如:
-- B_开头的表是各种单据, C_开头的表是各种合同协议, R_开头的表是各种报告, 其他为对象基本资料等
-- 表名后缀为_H的为历史备份表, 表名后缀为_L的为日志表, 表名后缀为_D的一般是明细表
-- 数量用DECIMAL(12,3), 价格用DECIMAL(10,2), 金额用DECIMAL(16,2)
-- 单据号的构成：两位大写单据类型+YYMMDD+6位顺序号（顺序号建议为月更新或日更新）
/*===============================================================*/
-- 基础表结构
-- 这些对象的修改都无相应模块, 由程序员或后台模块自动维护
-- ---------------------------------------------------------------
-- 序号表: Sequence
-- 简易词典表, 词典标题表: WordbookTitle, Wordbook
-- 系统配置表: Config
-- 单据类型表: BillType
-- 文档表: Document
-- ---------------------------------------------------------------
-- 核心对象表结构
-- 这些对象暂时都由直接模块完成, 如需使用单据完成, 再行修改
-- ---------------------------------------------------------------
-- 用户, 用户登录, 用户登录日志: User, UserLogin, UserLogin_L

/*==============================================================*/

set character_set_client      = utf8mb4;
set character_set_connection  = utf8mb4;
set character_set_database    = utf8mb4;
set character_set_results     = utf8mb4;
set character_set_server      = utf8mb4;

-- ----------------------------------------------------------------
-- 简易词典表和词典标题表: wordbookTitle, wordbook
-- 建立: inmyjs 20190101
-- WordbookTitle与Wordbook需建立外键
-- 所有关键字字母均需为大写
-- ----------------------------------------------------------------
DROP TABLE IF EXISTS wordbook;
DROP TABLE IF EXISTS wordbookTitle;
CREATE TABLE wordbookTitle
(
keyword				VARCHAR(30) NOT NULL			COMMENT '词典关键字',
keywordDESC		    TEXT NOT NULL					COMMENT '词典关键字说明',
CONSTRAINT PK_wordbookTitle PRIMARY KEY(keyword)
);
ALTER TABLE wordbookTitle COMMENT= '词典标题表';

CREATE TABLE wordbook
(
keyword				VARCHAR(30) NOT NULL			COMMENT '词典关键字',
wordValue			VARCHAR(30) NOT NULL			COMMENT '关键字的值',
wordDisplay		    VARCHAR(100) NOT NULL			COMMENT '关键字显示的中文值',
sortNo				INT DEFAULT 0 NOT NULL			COMMENT '显示顺序',
status				CHAR(1) DEFAULT '0' NOT NULL	COMMENT '字典状态(0=正常, S=失效)',
note				TEXT							COMMENT '备注',
CONSTRAINT PK_wordbook PRIMARY KEY(keyword,wordValue)
);
ALTER TABLE wordbook COMMENT= '简易词典表';

-- ----------------------------------------------------------------
-- region: region
-- 建立: inmyjs 20190101
-- ----------------------------------------------------------------
DROP TABLE IF EXISTS `region`;
CREATE TABLE `region` (
  `region_id` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `parent_id` smallint(5) unsigned NOT NULL DEFAULT '0',
  `region_name` varchar(120) NOT NULL DEFAULT '',
  `region_type` tinyint(1) NOT NULL DEFAULT '2',
  `agency_id` smallint(5) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`region_id`)
);

-- ----------------------------------------------------------------
-- 系统配置表: config
-- 建立: inmyjs 20190101
-- 该表由架构师维护, 在所有子系统和库里均相同
-- ----------------------------------------------------------------
DROP TABLE IF EXISTS config;
CREATE TABLE config
(
systemName			VARCHAR(30) NOT NULL			COMMENT '子系统的英文名',
systemCName		    VARCHAR(100) 			        COMMENT '子系统的中文名',
configName			VARCHAR(30) NOT NULL			COMMENT '用户配置的分组名称',
keyWord				VARCHAR(30) NOT NULL			COMMENT '配置参数关键字',
configValue		    VARCHAR(100) NOT NULL			COMMENT '配置参数的值',
configDefaultValue  VARCHAR(100) 			        COMMENT '配
[Msg] Finished - Unsuccessfully
--------------------------------------------------

**Comment by inmyjs** [comment]
mysql是什么版本，此脚本可在5.7上正常运行
